### ISSUE TITLE
How u parse floor? 

### ISSUE THREAD

**Issue by ninaprod** [synthonier/me-sniper#1]
Hey bro ! 
I'm currently writing sniper on GO
I didn't find the line of code where you parse the flora of the collection to catch cheap NFTs

**Comment by synthonier** [comment]
Hello!
Actually, I didn't implement this function, but you can easily do it with free official MagicEden API - https://api.magiceden.dev.
Or you can use my tiny package for this - https://github.com/synthonier/me-api, with GetStats() method.
If you need more information, you are welcome to my tg: @synthonier
